package pe.com.tintegro.sigs.dao;

import pe.com.tintegro.sigs.dto.request.EliminarAreaEspecialidadActividadGrupoOcupacionalJRequest;
import pe.com.tintegro.sigs.dto.request.InsertarAreaEspecialidadActividadGrupoOcupacionalJRequest;
import pe.com.tintegro.sigs.dto.request.ObtenerAreaEspecialidadActividadGrupoOcupacionalJRequest;
import pe.com.tintegro.sigs.dto.response.EliminarAreaEspecialidadActividadGrupoOcupacionalJResponse;
import pe.com.tintegro.sigs.dto.response.InsertarAreaEspecialidadActividadGrupoOcupacionalJResponse;
import pe.com.tintegro.sigs.dto.response.ObtenerAreaEspecialidadActividadGrupoOcupacionalJResponse;

public interface AreaEspecialidadActividadGrupoOcupacionalDAO 
{

	public InsertarAreaEspecialidadActividadGrupoOcupacionalJResponse insertarAreaEspecialidadActividadGrupoOcupacionalJ(InsertarAreaEspecialidadActividadGrupoOcupacionalJRequest request) throws Exception;
	public ObtenerAreaEspecialidadActividadGrupoOcupacionalJResponse obtenerAreaEspecialidadActividadGrupoOcupacionalJ(ObtenerAreaEspecialidadActividadGrupoOcupacionalJRequest request) throws Exception;
	public EliminarAreaEspecialidadActividadGrupoOcupacionalJResponse eliminarAreaEspecialidadActividadGrupoOcupacionalJ(EliminarAreaEspecialidadActividadGrupoOcupacionalJRequest request)throws Exception;	

}
